<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuxqIph\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuxqIph/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIuxqIph.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIuxqIph\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIuxqIph\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IuxqIph',
    'container.build_id' => 'e70a48a2',
    'container.build_time' => 1572967714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuxqIph');
