<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXobRWjt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXobRWjt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXobRWjt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXobRWjt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXobRWjt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XobRWjt',
    'container.build_id' => '4da10d5f',
    'container.build_time' => 1580755193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXobRWjt');
