<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3VHibs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3VHibs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD3VHibs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD3VHibs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD3VHibs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D3VHibs',
    'container.build_id' => '43076c03',
    'container.build_time' => 1579011726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3VHibs');
